apiVersion: v1
kind: Service
metadata:
  name: kaboom-events-service
  labels:
    service: kaboom-events
spec:
  selector:
    service: kaboom-events-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 8600
    nodePort: 30600
