apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaboom-web-deployment
spec:
  # below basically just a copy of a spec section from the replica set
  replicas: 2
  minReadySeconds: 10 # do not route requests until the service has run for 10''
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # one replica unavailable max
      maxSurge: 1         # 1 extra replica available max
  selector:
    matchLabels:
      service: kaboom-web-service
  template:
    # below basically just a copy of a pod without a name
    metadata:
      labels:
        version: v1.0.0
        service: kaboom-web-service
    spec:
      containers:
      - name: kaboom-web-service
        image: artemkv/kaboom-web-service:latest
        env:
        - name: SESSION_SECRET_KEY
          value: secret
        - name: MONGODB_CONNECTION_STRING
          value: mongodb://192.168.60.50:27017
        - name: DB_NAME
          value: kaboom
        ports:
        - containerPort: 8600
