apiVersion: v1
kind: Service
metadata:
  name: kaboom-web-service
  labels:
    service: kaboom-web
spec:
  selector:
    service: kaboom-web-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 8700
    nodePort: 30700
