apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaboom-stats-deployment
spec:
  # below basically just a copy of a spec section from the replica set
  replicas: 2
  minReadySeconds: 10 # do not route requests until the service has run for 10''
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1   # one replica unavailable max
      maxSurge: 1         # 1 extra replica available max
  selector:
    matchLabels:
      service: kaboom-stats-service
  template:
    # below basically just a copy of a pod without a name
    metadata:
      labels:
        version: v1.0.0
        service: kaboom-stats-service
    spec:
      containers:
      - name: kaboom-stats-service
        image: artemkv/kaboom-stats-service:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: 192.168.60.50:27017,192.168.60.51:27017
        - name: MONGO_CONNECTION_STRING
          value: mongodb://192.168.60.50:27017,192.168.60.51:27017
        - name: MONGO_DBNAME
          value: kaboom
        ports:
        - containerPort: 8500