apiVersion: v1
kind: Service
metadata:
  name: kaboom-stats-service
  labels:
    service: kaboom-stats
spec:
  selector:
    service: kaboom-stats-service
  type: NodePort
  ports:
  - protocol: TCP
    port: 8500
    nodePort: 30500
